-- MySQL Script generated by MySQL Workbench
-- mar. 02 oct. 2018 12:12:05 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema food_product
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_product` DEFAULT CHARACTER SET utf8 ;
USE `food_product` ;

-- -----------------------------------------------------
-- Table `food_product`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_product`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `store` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `nutrition_grade` VARCHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_product`.`substitution_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`substitution_product` (
  `produit_id` INT NOT NULL,
  `produit_id1` INT NOT NULL,
  PRIMARY KEY (`produit_id`, `produit_id1`),
  CONSTRAINT `fk_produit_has_produit_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `food_product`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_has_produit_produit2`
    FOREIGN KEY (`produit_id1`)
    REFERENCES `food_product`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_produit_has_produit_produit2_idx` ON `food_product`.`substitution_product` (`produit_id1` ASC);

CREATE INDEX `fk_produit_has_produit_produit1_idx` ON `food_product`.`substitution_product` (`produit_id` ASC);


-- -----------------------------------------------------
-- Table `food_product`.`category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`category_product` (
  `category_id` INT NOT NULL,
  `produit_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `produit_id`),
  CONSTRAINT `fk_category_has_produit_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_product`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_produit_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `food_product`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_category_has_produit_produit1_idx` ON `food_product`.`category_product` (`produit_id` ASC);

CREATE INDEX `fk_category_has_produit_category1_idx` ON `food_product`.`category_product` (`category_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
