-- MySQL Script generated by MySQL Workbench
-- mar. 27 nov. 2018 15:45:11 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema food_product
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_product` DEFAULT CHARACTER SET utf8 ;
USE `food_product` ;

-- -----------------------------------------------------
-- Table `food_product`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `store` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `nutrition_grade` VARCHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_product`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_product`.`category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`category_product` (
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  CONSTRAINT `fk_category_has_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_product`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `food_product`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_category_has_product_product1_idx` USING BTREE ON `food_product`.`category_product` (`product_id` ASC);

CREATE INDEX `fk_category_has_product_category_idx` ON `food_product`.`category_product` (`category_id` ASC);


-- -----------------------------------------------------
-- Table `food_product`.`substitution_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_product`.`substitution_product` (
  `product_id` INT NOT NULL,
  `product_id1` INT NOT NULL,
  PRIMARY KEY (`product_id`, `product_id1`),
  CONSTRAINT `fk_product_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `food_product`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_product_product2`
    FOREIGN KEY (`product_id1`)
    REFERENCES `food_product`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_product_has_product_product2_idx` ON `food_product`.`substitution_product` (`product_id1` ASC);

CREATE INDEX `fk_product_has_product_product1_idx` ON `food_product`.`substitution_product` (`product_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
